services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  booking_services:
    build:
      context: ./booking-services
      dockerfile: Dockerfile
    container_name: booking-services
    ports:
      - "8003:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - USER_SERVICES_DB=user_services_db
      - PARKING_SERVICES_DB=PARKING_SERVICES_DB

  user_services:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    container_name: user-services
    ports:
      - "8002:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - USER_SERVICES_DB=user_services_db

  parking_services:
    build:
      context: ./parking-services
      dockerfile: Dockerfile
    container_name: parking-services
    ports:
      - "8001:8000"
    depends_on:
      - mongo
  gateway-services:
    build: 
      context: ./gateway-api
      dockerfile: Dockerfile
    container_name: gateway-services
    ports:
      - "8000:8000"  # Expose the gateway to your host machine
    depends_on:
      - user_services
      - parking_services
      - booking_services

volumes:
  mongo_data:
